apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
#parameters:
  #datastoreurl: ds:///vmfs/volumes/5e93738f-6d9c6068-dcd3-801844f019d6/
  #storagepolicyname: "provision"  # Optional Parameter
  #csi.storage.k8s.io/fstype: "nfs4" # Optional Parameter