---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: cloud-controller-manager
    tier: control-plane
  name: vsphere-cloud-controller-manager
  namespace: kube-system
spec:
  containers:
    - name: vsphere-cloud-controller-manager
      image: gcr.io/cloud-provider-vsphere/cpi/release/manager:latest
      args:
        - --v=2
        - --cloud-config=/etc/cloud/vsphere.conf
        - --cloud-provider=vsphere
      volumeMounts:
        - mountPath: /etc/cloud
          name: cloud-config-volume
          readOnly: true
      resources:
        requests:
          cpu: 200m
  hostNetwork: true
  tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
  securityContext:
    runAsUser: 1001
  serviceAccountName: cloud-controller-manager
  volumes:
    - name: cloud-config-volume
      secret:
        secretName: vsphere-config-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: cloud-controller-manager
  name: vsphere-cloud-controller-manager
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 43001
      protocol: TCP
      targetPort: 43001
  selector:
    component: cloud-controller-manager
